services:
  mongodb:
    image: mongo:8.0.21
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - eicat-network
    restart: unless-stopped

  tei-stylesheets-api:
    build:
      context: ./tei-stylesheets-api
      dockerfile: dockerfile
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - eicat-network
    restart: unless-stopped
  grobid:
    image: grobid/grobid:0.8.2-full
    ports:
      - "8070:8070"
    environment:
      - JAVA_OPTS=-Xmx4g
    networks:
      - eicat-network
    restart: unless-stopped
  eicat-ai-api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - EICAT_GROBID_URL=http://grobid:8070
      - EICAT_TEI_URL=http://tei-stylesheets-api:8000
      - EICAT_MONGODB_URL=mongodb://mongodb:27017
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - AWS_REGION=${AWS_REGION:-eu-west-2}
    volumes:
      - ~/.aws:/root/.aws:ro
    depends_on:
      - grobid
      - tei-stylesheets-api
      - mongodb
    container_name: eicat-api
    networks:
      - eicat-network
    restart: unless-stopped
  eicat-ai-ui:
    build:
      context: ./ui
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - eicat-ai-api
    container_name: eicat-ui
    networks:
      - eicat-network
    restart: unless-stopped

networks:
  eicat-network:
    driver: bridge

