---
title: "Evaluation protocol"
authors:
  - name: "Matthew Coole"
    affiliations:
      - ref: ukceh
    email: matcoo@ceh.ac.uk
    orcid: https://orcid.org/my-orcid?orcid=0000-0002-9279-931X
affiliations:
  - id: ukceh
    name: UKCEH
    city: Lancaster
    state: Lancashire
---

This page will describe the evaluation protocol applied in OneStop Task 4.4.

To accurately assess the performance of the automatic impact extraction performed by the tool we can perform automatic comparison to the "gold-standard" set of extracted EICAT impact assessments already available on the GISD website. However this does not tell us about how well an LLM performs this task but simply how closely it can match the performance of a single human on the task. To understand the performance of an LLM on this task we must first assess how well humans agree when performing the task, if the EICAT guidelines are robust and unambiguous enoguh to avoid disagreements and how much ambiguity in reference texts might contribute to differences between human annotators.

# Inter Annotator Agreement (IAA)
To evaluate inter annotator agreement we propose taking a set of referenced texts and tasking multiple human annotators to perform an assessment as the would when performing an EICAT assessment. As such we can then analyse the Inter-Annotator Agreement (IAA) accross a range of reference texts.

## Paper Assignment
Our group of volunteer annotators will perform data extraction on 15 papers each. In order to achieve a good statistical coverage we will distribute papers based on @cameron2022balanced (BIBD) whereby all annotators will perform data extraction on a small block of papers, then pairwise extraction will be performed on a wider set. This ensures that we will be able to examine agreement across a large number of annotators on the core block and accross a wider number of papers on those annotated pairwise. Further to this we will stratify the block(s) based on the ecological system defined in the paper (marine, freshwater, terrestrial). This will allow us to examine any variablibity in IAA within systems.

Each annotator will therefore perform data extraction on 15 papers broken down as:

- 6 core papers (2 marine, 2 freshwater, 2 terrestrial)
- 9 papers additional papers (3 marine, 3 freshwater, 3 terrestrial)

This means that in total, assuming a pairwise grouping of the 9 additional papers and $n$ annotators, the total number of papers examined in the evaluation will be:
$6 + \frac{9n}{2}$. Assuming around $n \approx 10$ annotators this will yield $\approx 51$ papers.

## Metrics
There are a range of potential metrics that could be applied to assess IAA.

### Cohen's Kappa
@cohen1960coefficient's Kappa can be used for comparing the observations of two annotators assigning categorical labels per observation.
$$
\kappa = \frac{p_o - p_e}{1 - p_e}
$$

this corrects for any potential agreements that might occur by random chance where $p_o$ is the observed agreement and $p_e$ is the expected agreement based on:

$$
p_e = \frac{1}{N^2}\sum{n_{k1}n_{k2}}
$$

where $N$ is the number of observations and $n_{k1}$ and $n_{k2}$ are the number of times category $k$ has been labelled by annotators $1$ and $2$ respectively.

Whilst Cohen's Kappa is a very widely adopted metric and allows us to look at the difference agreement in categorical labels such as EICAT category level or mechanism, it only allows us to capture the agreement between 2 annotators. This means it could be applied when assessing the IAA for the pairwaise papers used in evaluation but not on the core block annotated by all.

### Krippendorff's alpha
Unlike Cohen's Kappa, @krippendorff1980content's alpha can allow us to examine the IAA between more than 2 annotators on the same item which makes it ideal for analysing the core block of papers, as well as being useful for those in the pairwise block. It is defined by:
$$
\alpha = 1 - \frac{D_o}{D_e}
$$
where $D_o$ is the disagreemnt observed amongst the annotators and $D_e$ is the expected disagreement.

## References

::: {#refs}
:::
